### ISSUE TITLE
Both plays can win in one game 

### ISSUE THREAD

**Issue by whykanishk** [tusharsadhwani/tic.py#1]
<img width="960" alt="tic" src="https://user-images.githubusercontent.com/42186454/83941409-b0f0d780-a808-11ea-9207-90ba8d04c875.png">

**Comment by tusharsadhwani** [comment]
Yup, issuing a fix right now.

**Comment by tusharsadhwani** [comment]
@kt26 you can check if it works now

**Comment by whykanishk** [comment]
Another bug found.

**Comment by kt26** [comment]
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/42186454/83942015-b1d83800-a80d-11ea-97fb-ea163279dd69.png">


It should not be a tie.

**Comment by whykanishk** [comment]
<img width="960" alt="TIC2" src="https://user-images.githubusercontent.com/42186454/83942024-cd434300-a80d-11ea-9c67-520e32e8484e.png">

It should not be a tie.

**Comment by tusharsadhwani** [comment]
Check now, `bugfix` branch @kt26

**Comment by whykanishk** [comment]
All fine
